#!/bin/sh

path="/mnt/tftp"

global.bootm.image="${path}/${global.user}-linux-${global.hostname}"

oftree="${path}/${global.user}-oftree-${global.hostname}"
if [ -f "${oftree}" ]; then
	global.bootm.oftree="$oftree"
fi

nfsroot="/srv/nfs"
bootargs-ip

initramfs="${path}/${global.user}-initramfs-${global.hostname}"
if [ -f "${initramfs}" ]; then
	global.bootm.initrd="$initramfs"
else
	global.linux.bootargs.dyn.root="rw root=/dev/nfs nfsroot=$nfsroot,v4,tcp"
fi
